var langs = {
  en: {
    txt1: "WARNING!",
    txt3: "question 1",
    txt5: "question 2",
    txt7: "question 3",
    txt9: "AGE",
    txt11: "Username",
    txt13: "Email",
    txt15: "Password",
    txt17: "thank you!",
    txt2: "You will see nude photos. Please be discreet.",
    txt4: "Many of these women are desperate single moms and cheating wives looking for some fun. They could be your neighbors or someone you know. Do you agree to keep the identity of these women a secret?",
    txt6: 'These women have asked us to not allow men that are seeking a "relationship". They only desire quick sex. Not dating. Do you agree to this request?',
    txt8: "Are you at least 25 years old? The women have requested that we not let those younger than 25 contact them because of past rude behavior by younger men.",
    txt10:
      "Because you will see explicit images, we need to know that you are over 25.",
    txt12: "Please enter your username",
    txt14: "Please enter your e-mail",
    txt16: "Please enter your password",
    txt18:
      'You may now see our list and photos of women who are in your area. Again, please keep their identity a secret. Click on the "Continue" button and search on the basis of your answers.',
    btnContinue: "Continue",
    btnYes: "yes",
    btnNo: "no",
    btnNext: "Next",
    btnBack: "Back",
    adult: "adult only",
    follow: "follow",
  },
  ar: {
    txt1: "تحذير!",
    txt3: "1 السؤال رقم",
    txt5: "2 السؤال رقم",
    txt7: "3 السؤال رقم",
    txt9: "العمر",
    txt11: "اسم المستخدم",
    txt13: "البريد الإلكتروني",
    txt15: "كلمة المرور",
    txt17: "شكراً لك!",
    txt2: "سترى صوراً عارية. يرجى توخي الحذر.",
    txt4: "العديد من هؤلاء النساء هن أمهات عازبات يائسات وزوجات خائنات يبحثن عن بعض المرح. يمكن أن يكونوا جيرانك أو أي شخص تعرفه. هل توافق على الحفاظ على سرية هوية هؤلاء النساء؟",
    txt6: 'لقد طلبت منا هؤلاء النساء ألا نسمح للرجال الذين يسعون إلى "علاقة عاطفية". حيث أنهن يرغبن في ممارسة الجنس السريع، بدون مواعدة. هل توافق على هذا الطلب؟',
    txt8: "هل عمرك 25 عاماً على الأقل؟ لقد طلبت النساء ألا نسمح لأولئك الذين تقل أعمارهم عن 25 عامًا بالاتصال بهم بسبب بعض التصرفات الفظة من قبل الشباب الأصغر سناً.",
    txt10: "نظرًا لأنك سترى صورًا جنسية، نحتاج إلى معرفة أنك أكبر من 25 عامًا.",
    txt12: "يرجى إدخال اسم المستخدم",
    txt14: "يرجى إدخال بريدك الإلكتروني",
    txt16: "يرجى إدخال كلمة مرورك",
    txt18:
      'يمكنك الآن مشاهدة قائمتنا وصور النساء الموجودات في منطقتك. مرة أخرى، يرجى الحفاظ على سرية هويتهم. انقر زر "استمر" وابحث بناءً على إجاباتك.',
    btnContinue: "استمر",
    btnYes: "لا",
    btnNo: " نعم",
    btnNext: "استمر",
    btnBack: " التالي",
    adult: "للبالغين فقط",
    follow: "الاشتراك",
  },
  az: {
    txt1: "DİQQƏT!",
    txt3: "sual 1",
    txt5: "sual 2",
    txt7: "sual 3",
    txt9: "YAŞ",
    txt11: "İstifadəçi adı",
    txt13: "Elektron poçt",
    txt15: "Şifrə",
    txt17: "Çox sağ ol!",
    txt2: "Çılpaq fotoları görəcəksiniz. Xahiş edirəm təmkinli olun.",
    txt4: "Bu qadınların çoxu ümidsiz tək moms və əyləncəli arvad axtaran qadınlardır. Onlar sizin qonşularınız və ya tanıdığınız biri ola bilər. Bu qadınların kimliyini gizli saxlamağa razısınız?",
    txt6: 'Bu qadınlar "əlaqələr" axtaran kişilərə icazə verməməyimizi istədi. Yalnız tez cinsi əlaqə arzulayırlar. Tanış deyiləm. Bu tələblə razısınız?',
    txt8: "Ən azı 25 yaşın var? Qadınlar, 25 yaşdan kiçik olanların, gənc kişilərin keçmiş kobud davranışlarına görə onlarla əlaqə yaratmamağımızı istədi.",
    txt10:
      "Açıq-saçıq görüntüləri görəcəyiniz üçün, 25 yaşdan yuxarı olduğunuzu bilməliyik.",
    txt12: "Zəhmət olmasa istifadəçi adınızı daxil edin",
    txt14: "Zəhmət olmasa elektron poçtunuzu daxil edin",
    txt16: "Şifrənizi daxil edin",
    txt18:
      'İndi siyahımızı və ərazinizdə olan qadınların fotolarını görə bilərsiniz. Yenə də şəxsiyyətlərini gizli saxla "Davam et" düyməsini vurun və cavablarınız əsasında axtarış aparın.',
    btnContinue: "Davam edin",
    btnYes: "Bəli",
    btnNo: "YOX",
    btnNext: "Davam edin",
    btnBack: "Geri",
    adult: "yalnız böyüklər",
    follow: "abunə olun",
  },
  tr: {
    txt1: "UYARI!",
    txt3: "soru 1",
    txt5: "soru 2",
    txt7: "soru 3",
    txt9: "YAŞ",
    txt11: "Kullanıcı adı",
    txt13: "E-posta",
    txt15: "Parola",
    txt17: "Teşekkür ederim!",
    txt2: "Çıplak fotoğraflar göreceksiniz. Lütfen sağduyulu olun.",
    txt4: "Bu kadınların çoğu umutsuz bekar anneler ve biraz eğlence arayan hile eşler. Komşularınız veya tanıdığınız biri olabilirler. Bu kadınların kimliğini gizli tutmayı kabul ediyor musunuz?",
    txt6: 'Bu kadınlar bizden "ilişki" arayan erkeklere izin vermemizi istedi. Sadece hızlı seks istiyorlar. Arkadaş değil. Bu talebi kabul ediyor musunuz?',
    txt8: "En az 25 yaşında mısın? Kadınlar, 25 yaşından küçüklerin, daha genç erkeklerin geçmiş kaba davranışları nedeniyle onlarla iletişim kurmasını istemedik.",
    txt10:
      "Müstehcen görüntüler göreceğiniz için 25 yaşından büyük olduğunuzu bilmemiz gerekir.",
    txt12: "Lütfen kullanıcı adınızı girin",
    txt14: "Lütfen E-postanızı girin",
    txt16: "Şifrenizi giriniz Lütfen",
    txt18:
      'Artık listemiz ve bölgenizdeki kadınların fotoğraflarını görebilirsiniz. Yine, lütfen kimliklerini bir sır olarak saklayın. "Devam" düğmesini tıklayın ve yanıtlarınıza göre arama yapın.',
    btnContinue: "Devam et",
    btnYes: "EVET",
    btnNo: "HAYIR",
    btnNext: "Devam et",
    btnBack: "Geri",
    adult: "sadece yetişkinlere özel",
    follow: "Abone",
  },
  uk: {
    txt1: "Увага!",
    txt3: "Питання 1",
    txt5: "Питання 2",
    txt7: "Питання 3",
    txt9: "Вік",
    txt11: "Ім'я користувача",
    txt13: "Електронна пошта",
    txt15: "Пароль",
    txt17: "Дякую!",
    txt2: "Ви побачите оголені фотографії. Будьте уважні.",
    txt4: "Багато з цих жінок - відчайдушні одинокі мами та обманюючі дружини, які шукають задоволення. Вони можуть бути вашими сусідами чи кимсь, кого ви знаєте. Чи погоджуєтесь ви зберігати особу цих жінок в таємниці?",
    txt6: 'Ці жінки попросили нас не допускати чоловіків, які шукають "стосунків". Вони бажають лише швидкого сексу. Не знайомства. Чи згодні ви з цим запитом?',
    txt8: "Вам щонайменше 25 років? Жінки просили, щоб ми не дозволяли контактувати з ними молодшим за 25 років через грубу поведінку молодих чоловіків.",
    txt10:
      "Оскільки ви побачите явні зображення, ми повинні знати, що вам старше 25 років.",
    txt12: "Введіть своє ім'я користувача",
    txt14: "Будь ласка, введіть свою електронну адресу",
    txt16: "Введіть свій пароль",
    txt18:
      'Тепер ви можете побачити наш список та фотографії жінок, які перебувають у вашому районі. Знову будь ласка, зберігайте їхню особу в таємниці. Клацніть на кнопку "Продовжити" та почніть пошук на основі ваших відповідей.',
    btnContinue: "Продовжити",
    btnYes: "так",
    btnNo: "ні",
    btnNext: "Далі",
    btnBack: "Назад",
    adult: "лише для дорослих",
    follow: "Підписатися",
  },
  ru: {
    txt1: "Внимание!",
    txt3: "Вопрос 1",
    txt5: "Вопрос 2",
    txt7: "Вопрос 3",
    txt9: "Возраст",
    txt11: "Имя пользователя",
    txt13: "Электронный адрес",
    txt15: "Пароль",
    txt17: "Спасибо!",
    txt2: "Вы увидите обнаженные фотографии. Пожалуйста, будьте осмотрительны.",
    txt4: "Многие из этих женщин - отчаянные одинокие мамы и обманывающие жены, ищущие веселья. Они могут быть вашими соседями или знакомыми. Согласны ли вы сохранить личность этих женщин в секрете?",
    txt6: 'Эти женщины просили нас не пропускать мужчин, которые ищут "отношения". Они только хотят быстрого секса. Без свиданий. Вы согласны с этим запросом?',
    txt8: "Вам уже исполнилось 25 лет? Женщины просили, чтобы мы не позволяли лицам моложе 25 лет, выходить на контакт с ними из-за предшествующего грубого поведения молодых парней.",
    txt10:
      "Поскольку вы увидите откровенные изображения, мы должны удостовериться, что вам больше 25 лет.",
    txt12: "Пожалуйста, введите имя пользователя",
    txt14: "Пожалуйста, введите свой адрес электронной почты",
    txt16: "Пожалуйста, введите пароль",
    txt18:
      "Теперь вы можете увидеть список и фотографии женщин, которые находятся в вашем районе. Будьте добры, держите их личность в секрете. Нажмите кнопку «Продолжить» и осуществляйте поиск на основе ваших ответов.",
    btnContinue: "Продолжить",
    btnYes: "ДА",
    btnNo: "НЕТ",
    btnNext: "Далее",
    btnBack: "Назад",
    adult: "только для взрослых",
    follow: "Подписаться",
  },
  fi: {
    txt1: "TÄRKEÄÄ!",
    txt3: "KYSYMYS 1",
    txt5: "KYSYMYS 2",
    txt7: "KYSYMYS 3",
    txt9: "Возраст",
    txt11: "Имя пользователя",
    txt13: "Электронный адрес",
    txt15: "Пароль",
    txt17: "KIITOS!",
    txt2: "Ennen kuin voimme näyttää sinulle lähelläsi asuvien ja seksiin juuri nyt halukkaiden naisten luettelon ja kuvat, meidän täytyy kysyä sinulta muutama kysymys.",
    txt4: "Monet näistä naisista ovat epätoivoisia sinkkuäitejä tai naimisissa olevia naisia, jotka ovat valmiita pettämään. He voivat olla naapureitasi tai tuntemiasi ihmisiä. Lupaatko pitää näiden naisen henkilöllisyyden salaisuutena?",
    txt6: "Nämä naiset ovat pyytäneet, ettemme salli suhdetta etsivien miesten ottaa heihin yhteyttä. He haluavat vain nopeaa seksiä, eivät deittailua. Suostutko tähän pyyntöön?",
    txt8: "Suostutko käyttämään kondomia harrastaessasi seksiä sivuston kautta tapaamasi partnerin kanssa?",
    txt10: "Olet yli 18-vuotias?",
    txt18:
      "Voit nyt tutustua alueesi naisten luetteloon ja kuviin. Kuten sanottu, pidäthän heidän henkilöllisyytensä salaisuutena.",
    btnContinue: "JATKA",
    btnNext: "JATKA",
    btnYes: "KYLLÄ",
    btnNo: "EI",
    adult: "adult only",
    follow: "Tilaa",
  },
  no: {
    txt1: "OBS!",
    txt3: "SPØRSMÅL 1",
    txt5: "SPØRSMÅL 2",
    txt7: "SPØRSMÅL 3",
    txt9: "Возраст",
    txt17: "TUSEN TAKK!",
    txt2: "Du kommer til å se nakenbilder. Vi ber deg om å være diskret.",
    txt4: "Mange av disse kvinnene er desperate enslige mødre og gifte kvinner som ønsker å jukse. De kan være dine naboer eller noen du kjenner. Er du enig i å beholde identiteten til disse kvinnene en hemmelighet?",
    txt6: 'Disse kvinnene har bedt oss om å ikke la dem se menn som søker en "forhold ". De bare ønsker rask sex. Ikke noe seriøst. Godtar du denne forespørselen?',
    txt8: "Samtykker du å bruke kondom når du har sex med en partner du har møtt på nettstedet vårt?",
    txt10:
      "Til slutt, er du minst 18 år gammel? Kvinnene har bedt om at vi ikke lar de som er under 18 kontakte dem på grunn av tidligere uhøflig oppførsel av yngre menn.",
    txt18:
      "Du kan nå se vår liste over kvinner som er i ditt område, og du kan se deres bilder. Vi ber deg igjen vennligst hold dems identitet hemmelig.",
    btnContinue: "FORTSETT",
    btnYes: "JA",
    btnNext: "FORTSETT",
    btnNo: "NEI",
    adult: "adult only",
    follow: "Abonnere",
  },
  ro: {
    txt1: "AVERTIZARE!",
    txt3: "intrebarea 1",
    txt5: "intrebarea 2",
    txt7: "intrebarea 3",
    txt9: "VÂRSTĂ",
    txt11: "Nume de utilizator",
    txt13: "E-mail",
    txt15: "Parola",
    txt17: "Mulțumesc!",
    txt2: "Veți vedea fotografii nud. Vă rugăm să fiți discret.",
    txt4: "Multe dintre aceste femei sunt mame singure disperate și soții care înșală în căutarea unor distracții. Ar putea fi vecinii tăi sau cineva cunoscut. Sunteți de acord să păstrați secret identitatea acestor femei?",
    txt6: "Aceste femei ne-au cerut să nu permitem bărbaților care caută o „relație”. Nu doresc decât sex rapid. Nu se intalneste. Sunteți de acord cu această solicitare?",
    txt8: "Ai cel puțin 25 ani? Femeile au solicitat să nu îi lăsăm pe cei mai mici de 25 ani să îi contacteze din cauza comportamentului nepoliticos al bărbaților mai tineri.",
    txt10:
      "Pentru că veți vedea imagini explicite, trebuie să știm că aveți peste 25 ani.",
    txt12: "Vă rugăm să introduceți numele de utilizator",
    txt14: "Vă rugăm să introduceți adresa dvs. de email",
    txt16: "Va rugam sa introduceti parola",
    txt18:
      "Acum puteți vedea lista noastră și fotografiile cu femeile din zona dvs. Din nou, vă rugăm să păstrați secretul identității lor. Faceți clic pe butonul „Continuați” și căutați pe baza răspunsurilor dvs.",
    btnContinue: "Continua",
    btnYes: "DA",
    btnNo: "NU",
    btnNext: "Următorul",
    btnBack: "Înapoi",
    adult: "doar pentru adulți",
    follow: "Abonati-va",
  },
  zh: {
    txt1: "警告！",
    txt3: "问题 1",
    txt5: "问题 2",
    txt7: "问题 3",
    txt9: "年龄",
    txt11: "用户名",
    txt13: "电子邮件",
    txt15: "密码",
    txt17: "谢谢！",
    txt2: "您会看到裸照。请谨慎",
    txt4: "这些女性很多都是绝望的单身妈妈，或是为了找乐子而出轨的人妻。可能是您的邻居或您认识的人。您是否同意对她们的身份保密？",
    txt6: "这些女性要求过滤掉寻求“恋情”的男性。她们只需要快速性爱，而不是约会。您是否接受这种要求？",
    txt8: "您是否已满 25 岁？这些女性要求不要让 25 岁以下的未成年人联系她们，因为曾经遭受过年轻男性的粗鲁行为。",
    txt10: "因为会看到清晰图像，我们需要知道您已经 25 岁以上。",
    txt12: "请填写用户名",
    txt14: "请填写您的电子邮件",
    txt16: "请填写密码",
    txt18:
      "您可以看到您所在区域的相关女性的名单和照片。再次强调，请对她们的身份保密。点击“继续”按钮，在您答案的基础上搜索。",
    btnContinue: "继续",
    btnYes: "是",
    btnNo: "否",
    btnNext: "下一个",
    btnBack: "上一个",
    adult: "仅限成人",
    follow: "订阅",
  },
  pl: {
    txt1: "OSTRZEŻENIE!",
    txt3: "Pytanie 1",
    txt5: "Pytanie 2",
    txt7: "Pytanie 3",
    txt9: "WIEK",
    txt11: "Nazwa Użytkownika",
    txt13: "E-mail",
    txt15: "Hasło",
    txt17: "Dziękuję Ci!",
    txt2: "Zobaczysz nagie zdjęcia. Bądź dyskretny.",
    txt4: "Wiele z tych kobiet jest zrozpaczonymi samotnymi mamami i zdradzającymi żonami szukającymi dobrej zabawy. Mogą to być twoi sąsiedzi lub ktoś, kogo znasz. Czy zgadzasz się zachować tożsamość tych kobiet w tajemnicy?",
    txt6: "Te kobiety poprosiły nas, abyśmy nie zezwalali mężczyznom, którzy szukają „związku”. Chcą tylko szybkiego seksu. Nie umawiać się Czy zgadzasz się na tę prośbę?",
    txt8: "czy masz przynajmniej 25 lat? Kobiety poprosiły, aby nie pozwalać osobom młodszym niż 25 lat kontaktować się z nimi z powodu niegrzecznych zachowań młodszych mężczyzn.",
    txt10:
      "Ponieważ zobaczysz wyraźne obrazy, musimy wiedzieć, że masz ukończone 25 lat.",
    txt12: "Proszę, wpisz swoją nazwę użytkownika",
    txt14: "Proszę podać swój adres e-mail",
    txt16: "Wprowadź hasło",
    txt18:
      "Możesz teraz zobaczyć naszą listę i zdjęcia kobiet z Twojej okolicy. Ponownie, proszę, zachowaj ich tożsamość w tajemnicy. Kliknij przycisk „Kontynuuj” i wyszukaj na podstawie swoich odpowiedzi.",
    btnContinue: "Kontyntynuj",
    btnYes: "TAK",
    btnNo: "NIE",
    btnNext: "Dalej",
    btnBack: "Wstecz",
    adult: "tylko dla dorosłych",
    follow: "Subskrybuj",
  },
  it: {
    txt1: "ATTENZIONE!",
    txt3: "Domanda 1",
    txt5: "Domanda 2",
    txt7: "Domanda 3",
    txt9: "ETÀ",
    txt11: "Nome utente",
    txt13: "Email",
    txt15: "Password",
    txt17: "Grazie!",
    txt2: "Potresti visualizzare foto di nudo. Ti preghiamo di essere discreto.",
    txt4: "Molte di queste donne sono mamme single disperate e mogli che tradiscono i loro mariti in cerca di divertimento. Potrebbero essere le tue vicine di casa o persone di tua conoscenza. Accetti di mantenere segreta l'identità di queste donne?",
    txt6: 'Queste donne ci hanno chiesto di non permettere agli uomini che cercano una "relazione seria" di contattarle. Vogliono solo sesso senza impegni. Nessun appuntamento serio. Accetti questa richiesta?',
    txt8: "Hai almeno 25 anni? Le donne ci hanno chiesto di non permettere a persone di età inferiore ai 25 anni di contattarle a causa del comportamento maleducato di alcuni giovani uomini in passato.",
    txt10:
      "Poiché visualizzerai immagini esplicite, dobbiamo essere sicuri che hai più di 25 anni.",
    txt12: "Ti preghiamo di inserire il tuo nome utente",
    txt14: "Ti preghiamo di inserire la tua email",
    txt16: "Ti preghiamo di inserire la tua password",
    txt18:
      'Adesso puoi visualizzare l\'elenco e le foto delle donne che si trovano nella tua zona. Ancora una volta, ti preghiamo di mantenere segreta la loro identità. Clicca sul pulsante "Continua" e cerca utenti in base alle tue risposte.',
    btnContinue: "Continua",
    btnYes: "SÌ",
    btnNo: "NO",
    btnNext: "Avanti",
    btnBack: "Indietro",
    adult: "Solo adulti",
    follow: "Iscriviti",
  },
  fr: {
    txt1: "AVERTISSEMENT!",
    txt3: "question 1",
    txt5: "question 2",
    txt7: "question 3",
    txt9: "ÂGE",
    txt11: "Nom d'utilisateur",
    txt13: "Email",
    txt15: "Mot de passe",
    txt17: "Merci !",
    txt2: "Vous verrez des photos nues. Soyez discret.",
    txt4: "Beaucoup de ces femmes sont des mères célibataires désespérées et des femmes infidèles à la recherche de plaisir. Elles pourraient être vos voisines ou quelqu'un que vous connaissez. Acceptez-vous de garder secrète l'identité de ces femmes ?",
    txt6: 'Ces femmes nous ont demandé de ne pas autoriser les hommes qui recherchent une "relation". Elles ne désirent que du sexe rapide. Ne pas sortir ensemble. Acceptez-vous cette demande ?',
    txt8: "Avez-vous au moins 25 ans ? Les femmes ont demandé que nous ne laissions pas les jeunes de moins de 25 ans les contacter en raison du comportement grossier des hommes plus jeunes.",
    txt10:
      "Parce que vous verrez des images explicites, nous devons savoir que vous avez plus de 25 ans.",
    txt12: "S'il vous plaît entrez votre nom d'utilisateur",
    txt14: "Veuillez saisir votre e-mail",
    txt16: "S'il vous plait entrez votre mot de passe",
    txt18:
      'Vous pouvez maintenant voir notre liste et des photos de femmes qui sont dans votre région. Encore une fois, veuillez garder leur identité secrète. Cliquez sur le bouton "Continuer" et effectuez une recherche sur la base de vos réponses.',
    btnContinue: "Continuer",
    btnYes: "OUI",
    btnNo: "NON",
    btnNext: "suivant",
    btnBack: "Retour",
    adult: "adulte seulement",
    follow: "S'abonner",
  },
  hr: {
    txt1: "UPOZORENJE!",
    txt3: "Pitanje 1",
    txt5: "Pitanje 2",
    txt7: "Pitanje 3",
    txt9: "DOB",
    txt11: "Korisničko ime",
    txt13: "E-mail",
    txt15: "Zaporka",
    txt17: "Hvala vam!",
    txt2: "Vidjet ćete gole fotografije. Molimo budite diskretni.",
    txt4: "Mnoge od tih žena očajne su samohrane mame i varaju supruge koje traže zabavu. Mogli bi vam biti susjedi ili netko koga poznajete. Slažete li se da identitet tih žena čuvate u tajnosti?",
    txt6: 'Te žene su nas molile da ne dopustimo muškarcima koji traže "vezu". Žele samo brzi seks. Ne izlazi. Slažete li se sa ovim zahtjevom?',
    txt8: "Imate li barem 25 godina? Žene su zatražile da im ne dopustimo da kontaktiraju one mlađe od 25 godina zbog nepristojnog ponašanja mlađih muškaraca.",
    txt10:
      "Budući da ćete vidjeti eksplicitne slike, moramo znati da imate više od 25 godina.",
    txt12: "Unesite svoje korisničko ime",
    txt14: "Molimo unesite svoj e-mail",
    txt16: "Molimo unesite svoju lozinku",
    txt18:
      'Sada možete vidjeti naš popis i fotografije žena koje se nalaze u vašem kraju. Molim vas, čuvajte njihov identitet u tajnosti. Kliknite gumb "Nastavi" i pretražite na osnovu vaših odgovora.',
    btnContinue: "Nastaviti",
    btnYes: "DA",
    btnNo: "NE",
    btnNext: "Naprijed",
    btnBack: "Nazad",
    adult: "samo za odrasle",
    follow: "Pretplatite se",
  },
  es: {
    txt1: "¡ADVERTENCIA!",
    txt3: "Pregunta 1",
    txt5: "Pregunta 2",
    txt7: "Pregunta 3",
    txt9: "EDAD",
    txt11: "Nombre de usuario",
    txt13: "Correo electrónico",
    txt15: "Contraseña",
    txt17: "¡Gracias!",
    txt2: "Vas a ver fotos con desnudos. Por favor, sé discreto.",
    txt4: "Muchas de estas mujeres son madres solteras o casadas infieles que quieren pasarlo bien. Podrían ser tus vecinas o alguien a quien conoces. ¿Aceptas mantener en secreto la identidad de estas mujeres?",
    txt6: "Estas mujeres nos han pedido que no enseñemos sus perfiles a hombres que buscan una “relación”. Solo quieren sexo rápido. No quieren tener citas románticas. ¿Aceptas esta condición?",
    txt8: "¿Tienes al menos 25 años? Debido a malas experiencias relacionadas con el comportamiento de hombres jóvenes, las mujeres nos han pedido que no dejemos que contacten con ellas los menores de 25 años.",
    txt10:
      "Dado que vas a ver imágenes explícitas, necesitamos saber que tienes más de 25 años.",
    txt12: "Por favor, introduce tu nombre de usuario",
    txt14: "Por favor, introduce tu correo electrónico",
    txt16: "Por favor, introduce tu contraseña",
    txt18:
      'Ahora puedes ver nuestra lista de mujeres de tu zona y sus fotos. Te pedimos una vez más que mantengas su identidad en secreto. Haz clic en el botón “Continuar" y efectúa una búsqueda conforme a tus respuestas.',
    btnContinue: "Continuar",
    btnYes: "SÍ",
    btnNo: "NO",
    btnNext: "Siguiente",
    btnBack: "Anterior",
    adult: "Solo adultos",
    follow: "Suscríbete",
  },
  hu: {
    txt1: "FIGYELEM!",
    txt3: "1. kérdés",
    txt5: "2. kérdés",
    txt7: "3. kérdés",
    txt9: "KOR",
    txt11: "Felhasználónév",
    txt13: "Email",
    txt15: "Jelszó",
    txt17: "Köszönöm!",
    txt2: "Látni fogja a meztelen fényképeket. Kérjük, legyen óvatos.",
    txt4: "Ezek közül a nők közül sokan kétségbeesett egyedülálló anyukák és csaló feleségek, akik szórakozást keresnek. Lehet, hogy a szomszédok vagy valaki, akit ismersz. Egyetért-e azzal, hogy titokban tartja e nők identitását?",
    txt6: "Ezek a nők arra kérték bennünket, hogy ne engedjük be a férfiakat, akik „kapcsolatot” keresnek. Csak a gyors szexre vágynak. Nem randevú. Ön elfogadja ezt a kérést?",
    txt8: "Legalább 25 éves vagy? A nők azt kérték, hogy ne engedjük, hogy a 25 éven aluli gyermekek kapcsolatba lépjenek velük a fiatalabb férfiak korábbi durva viselkedése miatt.",
    txt10:
      "Mivel explicit képeket fog látni, tudnunk kell, hogy 25 évesnél idősebb.",
    txt12: "Kérjük, adja meg felhasználónevét",
    txt14: "Kérem, írja be az e-mail címét",
    txt16: "Kérem írja be a jelszavát",
    txt18:
      'Most láthatja a környékünkön lévő nők listáját és fényképeit. Ismét kérjük, tartsa titokban titkát. Kattintson a "Folytatás" gombra, és válaszok alapján keressen.',
    btnContinue: "Folytatni",
    btnYes: "IGEN",
    btnNo: "NEM",
    btnNext: "következő",
    btnBack: "Vissza",
    adult: "csak felnőtt",
    follow: "Iratkozz fel",
  },
  pt: {
    txt1: "ATENÇÃO!",
    txt3: "questão 1",
    txt5: "questão 2",
    txt7: "questão 3",
    txt9: "IDADE",
    txt11: "Nome de utilizador",
    txt13: "Endereço de e-mail",
    txt15: "Palavra-passe",
    txt17: "obrigado!",
    txt2: "Vais ver fotos com nudez. Por favor sê discreto.",
    txt4: "Muitas destas mulheres são mães desesperadas e cornudas que procuram alguma diversão. Podem até ser tuas vizinhas ou alguém que conheces. Comprometes-te a manter a identidade destas mulheres secreta?",
    txt6: 'Estas mulheres pediram-nos para não aceitar homens que procuram uma "relação". Elas apenas querem uma queca rápida. Não querem namoro. Concordas?',
    txt8: "És maior de idade? Estas mulheres pediram para que não permitissemos que homens com menos de 25 anos as contactassem, pois já houve casos de comportamento rude por parte de menores.",
    txt10:
      "Uma vez que irás ver imagens explicítas, temos que garantir que tens pelo menos 25 anos.",
    txt12: "Por favor introduz o teu nome de utilizador",
    txt14: "Por favor insere o teu e-mail",
    txt16: "Por favor insere a tua palavra-passe",
    txt18:
      'Já podes ver a nossa lista e fotos de mulheres na tua zona. Novamente, por favor mantém a sua identidade secreta. Clica em "Continuar" e pesquisa com base nas tuas respostas.',
    btnContinue: "Continuar",
    btnYes: "SIM",
    btnNo: "NÃO",
    btnNext: "Seguinte",
    btnBack: "Anterior",
    adult: "para adultos apenas",
    follow: "Se inscrever",
  },
  vi: {
    txt1: "CẢNH BÁO!",
    txt3: "câu hỏi 1",
    txt5: "câu hỏi 2",
    txt7: "câu hỏi 3",
    txt9: "TUỔI TÁC",
    txt11: "tên tài khoản",
    txt13: "E-mail",
    txt15: "Mật khẩu",
    txt17: "Cảm ơn bạn!",
    txt2: "Bạn sẽ thấy ảnh khỏa thân. Xin hãy cẩn thận.",
    txt4: "Nhiều người trong số những người phụ nữ này đang tuyệt vọng làm mẹ đơn thân và những người vợ lừa dối để tìm kiếm niềm vui. Họ có thể là hàng xóm của bạn hoặc người mà bạn biết. Bạn có đồng ý giữ bí mật danh tính của những người phụ nữ này không?",
    txt6: 'Những người phụ nữ này đã yêu cầu chúng tôi không cho phép những người đàn ông đang tìm kiếm một "mối quan hệ". Họ chỉ ham muốn tình dục nhanh chóng. Không hẹn hò. Bạn có đồng ý với yêu cầu này không?',
    txt8: "Bạn ít nhất 25 tuổi? Những người phụ nữ đã yêu cầu chúng tôi không để những người dưới 25 tuổi liên lạc với họ vì những hành vi thô lỗ trong quá khứ của những người đàn ông trẻ hơn.",
    txt10:
      "Bởi vì bạn sẽ thấy hình ảnh rõ ràng, chúng tôi cần biết rằng bạn trên 25 tuổi.",
    txt12: "Xin hãy điền tên đăng nhập",
    txt14: "Vui lòng nhập email",
    txt16: "Vui lòng nhập mật khẩu của bạn",
    txt18:
      'Bây giờ bạn có thể xem danh sách của chúng tôi và hình ảnh của những người phụ nữ trong khu vực của bạn. Một lần nữa, xin vui lòng giữ bí mật danh tính của họ. Nhấp vào nút "Tiếp tục" và tìm kiếm trên cơ sở câu trả lời của bạn.',
    btnContinue: "Tiếp tục",
    btnYes: "CÓ",
    btnNo: "KHÔNG",
    btnNext: "Tiếp theo",
    btnBack: "Quay lại",
    adult: "chỉ người lớn",
    follow: "Đăng kí",
  },
  cs: {
    txt1: "VAROVÁNÍ!",
    txt3: "Otázka 1",
    txt5: "Otázka 2",
    txt7: "Otázka 3",
    txt9: "STÁŘÍ",
    txt11: "Uživatelské jméno",
    txt13: "E-mailem",
    txt15: "Heslo",
    txt17: "Děkuji!",
    txt2: "Uvidíte nahé fotografie. Buďte diskrétní.",
    txt4: "Mnoho z těchto žen jsou zoufalé svobodné maminky a podvádějící manželky hledající nějakou zábavu. Mohli by to být vaši sousedé nebo někdo, koho znáte. Souhlasíte, že budete udržovat identitu těchto žen v tajnosti?",
    txt6: "Tyto ženy nás požádaly, abychom nedovolili mužům, kteří hledají „vztah“. Chtějí jen rychlý sex. Ne randění. Souhlasíte s touto žádostí?",
    txt8: "Máte nejméně 25 let? Ženy požádaly, abychom nedovolili těm mladším 25 let, aby je kontaktovali kvůli minulému hrubému chování mladších mužů.",
    txt10:
      "Protože uvidíte explicitní obrázky, musíme vědět, že máte více než 25 let.",
    txt12: "Zadejte své uživatelské jméno",
    txt14: "Zadejte svůj e-mail",
    txt16: "Prosím zadejte své heslo",
    txt18:
      'Nyní můžete vidět náš seznam a fotografie žen, které jsou ve vaší oblasti. Znovu udržujte jejich identitu v tajnosti. Klikněte na tlačítko "Pokračovat" a hledejte na základě vašich odpovědí.',
    btnContinue: "Pokračovat",
    btnYes: "ANO",
    btnNo: "ŽÁDNÉ",
    btnNext: "další",
    btnBack: "Zpět",
    adult: "pouze pro dospělé",
    follow: "Odebírat",
  },
  sr: {
    txt1: "УПОЗОРЕЊЕ!",
    txt3: "Питање 1",
    txt5: "Питање 2",
    txt7: "Питање 3",
    txt9: "АГЕ",
    txt11: "Корисничко име",
    txt13: "Емаил",
    txt15: "Лозинка",
    txt17: "Хвала вам!",
    txt2: "Видећете голе фотографије. Молимо будите дискретни.",
    txt4: "Многе од ових жена су очајне самохране маме и варају супруге које траже забаву. Они могу бити ваши сусједи или неко кога познајете. Да ли се слажете да идентитет тих жена чувате у тајности?",
    txt6: "Те жене су нас замолиле да не дозволимо мушкарцима који траже „везу“. Желе само брзи секс. Не излази. Да ли се слажете са овим захтевом?",
    txt8: "Да ли имате најмање 25 година? Жене су затражиле да им не дозволимо да контактирају оне млађе од 25 година због непристојног понашања млађих мушкараца.",
    txt10:
      "Пошто ћете видети експлицитне слике, морамо знати да имате више од 25 година",
    txt12: "Молимо унесите своје корисничко име",
    txt14: "Молимо унесите свој е-маил",
    txt16: "Молим вас унесите вашу шифру",
    txt18:
      'Сада можете видети нашу листу и фотографије жена које се налазе у вашем крају. Молим вас, чувајте њихов идентитет у тајности. Кликните на дугме "Настави" и претражите на основу ваших одговора.',
    btnContinue: "Настави",
    btnYes: "ДА",
    btnNo: "НЕ",
    btnNext: "на следеће",
    btnBack: "Натраг",
    adult: "само за одрасле",
    follow: "претплатити се",
  },
  el: {
    txt1: "ΠΡΟΕΙΔΟΠΟΙΗΣΗ!",
    txt3: "Ερώτηση 1",
    txt5: "Ερώτηση 2",
    txt7: "Ερώτηση 3",
    txt9: "ΗΛΙΚΙΑ",
    txt11: "Όνομα χρήστη",
    txt13: "ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
    txt15: "Κωδικός πρόσβασης",
    txt17: "Σας ευχαριστώ!",
    txt2: "Θα δείτε γυμνές φωτογραφίες. Να είστε διακριτικοί.",
    txt4: "Πολλές από αυτές τις γυναίκες είναι απεγνωσμένες μονομαχίες και εξαπατώντας τις γυναίκες αναζητώντας κάποια διασκέδαση. Θα μπορούσαν να είναι οι γείτονές σας ή κάποιος που γνωρίζετε. Συμφωνείτε να κρατήσετε μυστική την ταυτότητα αυτών των γυναικών;",
    txt6: 'Αυτές οι γυναίκες μας ζήτησαν να μην επιτρέψουμε στους άνδρες που αναζητούν μια "σχέση". Απλώς επιθυμούν γρήγορο σεξ. Δεν χρονολογείται. Συμφωνείτε με αυτό το αίτημα;',
    txt8: "Είστε τουλάχιστον 25 ετών; Οι γυναίκες ζήτησαν να μην τους αφήσουμε να έρθουν σε επαφή με όσους είναι κάτω των 25 ετών λόγω προηγούμενης αγενής συμπεριφοράς των νεότερων ανδρών.",
    txt10:
      "Επειδή θα δείτε ρητές εικόνες, πρέπει να ξέρετε ότι είστε άνω των 25 ετών.",
    txt12: "Εισαγάγετε το όνομα χρήστη σας",
    txt14: "Παρακαλώ εισάγετε το e-mail σας",
    txt16: "Παρακαλώ εισάγετε τον κωδικό σας",
    txt18:
      'Τώρα μπορείτε να δείτε τη λίστα και τις φωτογραφίες των γυναικών που βρίσκονται στην περιοχή σας. Και πάλι, παρακαλώ κρατήστε την ταυτότητά τους μυστική. Κάντε κλικ στο κουμπί "Συνέχεια" και αναζητήστε με βάση τις απαντήσεις σας.',
    btnContinue: "Να συνεχίσει",
    btnYes: "ΝΑΙ",
    btnNo: "ΟΧΙ",
    btnNext: "Επόμενο",
    btnBack: "Επιστροφή",
    adult: "μόνο για ενήλικες",
    follow: "Εγγραφείτε",
  },
  th: {
    txt1: "คำเตือน!",
    txt3: "คำถามที่ 1",
    txt5: "คำถามที่ 2",
    txt7: "คำถามที่ 3",
    txt9: "อายุ",
    txt11: "ชื่อผู้ใช้",
    txt13: "อีเมล์",
    txt15: "รหัสผ่าน",
    txt17: "ขอขอบคุณ!",
    txt2: "คุณจะเห็นภาพเปลือย โปรดระมัดระวัง",
    txt4: "ผู้หญิงเหล่านี้หลายคนหมดหวังกับคุณแม่โสดและภรรยานอกใจที่กำลังมองหาความสนุกสนาน พวกเขาอาจเป็นเพื่อนบ้านของคุณหรือคนที่คุณรู้จัก คุณเห็นด้วยที่จะรักษาความลับของผู้หญิงเหล่านี้หรือไม่?",
    txt6: 'ผู้หญิงเหล่านี้ขอให้เราไม่อนุญาตให้ผู้ชายที่กำลังมองหา "ความสัมพันธ์" พวกเขาต้องการเพียงเพศที่รวดเร็ว ไม่ออกเดท คุณเห็นด้วยกับคำขอนี้หรือไม่?',
    txt8: "คุณอายุอย่างน้อย 25 ปี? ผู้หญิงขอให้เราไม่อนุญาตให้เด็กอายุน้อยกว่า 25 ปีติดต่อพวกเขาเพราะพฤติกรรมที่หยาบคายในอดีตโดยชายหนุ่ม",
    txt10: "เนื่องจากคุณจะเห็นภาพที่ชัดเจนเราจำเป็นต้องรู้ว่าคุณอายุเกิน 25 ปี",
    txt12: "กรุณาใส่ชื่อผู้ใช้ของคุณ",
    txt14: "กรุณากรอกอีเมลของคุณ",
    txt16: "กรุณาใส่รหัสผ่านของคุณ",
    txt18:
      'ตอนนี้คุณสามารถดูรายการและรูปภาพของผู้หญิงที่อยู่ในพื้นที่ของคุณ อีกครั้งโปรดเก็บข้อมูลเป็นความลับ คลิกที่ปุ่ม "ดำเนินการต่อ" และค้นหาตามคำตอบของคุณ',
    btnContinue: "ต่อ",
    btnYes: "ใช่",
    btnNo: "ไม่ใช่",
    btnNext: "ถัดไป",
    btnBack: "ย้อนกลับ",
    adult: "ผู้ใหญ่เท่านั้น",
    follow: "ติดตาม",
  },
  de: {
    txt1: "WARNUNG!",
    txt3: "Frage 1",
    txt5: "Frage 2",
    txt7: "Frage 3",
    txt9: "ALTER",
    txt11: "Benutzername",
    txt13: "E-Mail-Adresse",
    txt15: "Passwort",
    txt17: "Vielen Dank!",
    txt2: "Sie werden Nacktfotos sehen. Bitte seien Sie diskret.",
    txt4: "Viele dieser Frauen sind verzweifelte alleinerziehende Mütter und verheiratete Frauen, die auf der Suche nach etwas Spaß sind. Es könnte Ihre Nachbarin oder jemand sein, den Sie kennen. Sind Sie damit einverstanden, die Identität dieser Frauen geheim zu halten?",
    txt6: 'Diese Frauen haben uns gebeten, keine Männer zuzulassen, die auf der Suche nach einer "Beziehung" sind. Sie wünschen nur schnellen Sex. Keine Verabredungen. Stimmen Sie dieser Bitte zu?',
    txt8: "Sind Sie mindestens 30 Jahre alt? Die Frauen haben darum gebeten, dass wir nicht zulassen, dass sich Personen unter 30 Jahren wegen unhöflichen Verhaltens jüngerer Männer mit ihnen in Verbindung setzen.",
    txt10:
      "Da Sie explizite Bilder sehen, müssen wir wissen, dass Sie über 30 Jahre alt sind.",
    txt12: "Bitte geben Sie Ihren Benutzernamen ein.",
    txt14: "Bitte geben Sie Ihre E-Mail-Adresse ein.",
    txt16: "Bitte stellen Sie ein Passwort zur Verfügung.",
    txt18:
      'Sie können jetzt auf unsere Liste und Fotos von Frauen zugreifen, die in Ihrer Nähe sind. Bitte halten Sie ihre Identität geheim. Klicken Sie auf die Schaltfläche "Weiter" und starten Sie die Suche anhand Ihrer Antworten.',
    btnContinue: "Weiter",
    btnYes: "JA",
    btnNo: "NEIN",
    btnNext: "Weiter",
    btnBack: "Zurück",
    adult: "Nur für Erwachsene",
    follow: "Jetzt abonnieren",
  },
  da: {
    txt1: "Advarsel!",
    txt3: "spørgsmål 1",
    txt5: "spørgsmål 2",
    txt7: "spørgsmål 3",
    txt9: "ALDER",
    txt11: "Brugernavn",
    txt13: "Email",
    txt15: "Adgangskode",
    txt17: "Tak!",
    txt2: "Du vil se nøgne billeder. Vær diskret.",
    txt4: "Mange af disse kvinder er desperate enlige mødre og utro hustruer, som er på udkig efter noget sjov. De kan være dine naboer eller nogen, du kender. Er du enig i at holde disse kvinders identitet hemmelig?",
    txt6: 'Disse kvinder har bedt os om ikke at tillade mænd, der leder efter et "forhold". De ønsker kun hurtig sex. Ikke dating. Er du enig i denne anmodning?',
    txt8: "Er du mindst 25 år? Kvinderne har anmodet om, at vi ikke lader personer, som er yngre end 25, kontakte dem på grund af tidligere uhøflig opførsel fra yngre mænd.",
    txt10:
      "Da du vil se eksplicitte billeder, er vi nødt til at vide, om du er over 25 år.",
    txt12: "Indtast dit brugernavn",
    txt14: "Indtast din email",
    txt16: "Indtast venligst din adgangskode",
    txt18:
      'Du kan nu se vores liste og billeder af kvinder, som er i dit område. Hold venligst deres identitet hemmelig. Klik på knappen "Fortsæt" og søg på baggrund af dine svar.',
    btnContinue: "Fortsæt",
    btnYes: "JA",
    btnNo: "NEJ",
    btnNext: "Næste",
    btnBack: "Tilbage",
    adult: "kun for voksne",
    follow: "Abonner",
  },
  nl: {
    txt1: "Waarschuwing!",
    txt3: "Vraag 1",
    txt5: "Vraag 2",
    txt7: "Vraag 3",
    txt9: "LEEFTIJD",
    txt11: "Gebruikersnaam",
    txt13: "E-mail",
    txt15: "Wachtwoord",
    txt17: "dank je!",
    txt2: "Je zal naaktfoto's zien. Graag discreet zijn.",
    txt4: "Veel van deze vrouwen zijn wanhopige alleenstaande moeders en vreemdgaande vrouwen die op zoek zijn naar plezier. Ze zouden je buren kunnen zijn, of iemand die je kent. Ga je akkoord met het geheimhouden van de identiteit van deze vrouwen?",
    txt6: "Deze vrouwen hebben ons gevraagd geen mannen toe te staan ​​die een 'relatie' zoeken. Ze verlangen alleen naar snelle seks. Geen dating. Gaat u akkoord met dit verzoek?",
    txt8: "Ben je minstens 25 jaar oud? De vrouwen hebben gevraagd om mannen onder de 25 jaar te vermijden vanwege onbeleefd gedrag van jongere mannen.",
    txt10:
      "Omdat je expliciete afbeeldingen zal zien, moeten we weten dat je ouder dan 25 bent.",
    txt12: "Voer je gebruikersnaam in",
    txt14: "Graag je e-mailadres invullen",
    txt16: "Voer je wachtwoord in",
    txt18:
      'Mogelijk zie je nu onze lijst en foto\'s van vrouwen in uw omgeving. Nogmaals, houd hun identiteit geheim. Klik op de knop "Doorgaan" en zoek op basis van jouw antwoorden.',
    btnContinue: "Doorgaan",
    btnYes: "JA",
    btnNo: "NEE",
    btnNext: "Volgende",
    btnBack: "Terug",
    adult: "Alleen volwassenen",
    follow: "Abonneren",
  },
  sv: {
    txt1: "VARNING!",
    txt3: "fråga 1",
    txt5: "fråga 2",
    txt7: "fråga 3",
    txt9: "ÅLDER",
    txt11: "Användarnamn",
    txt13: "E-post",
    txt15: "Lösenord",
    txt17: "tack!",
    txt2: "Du kommer att se nakenbilder. Respektera användarnas integritet",
    txt4: "Många av dessa kvinnor är ofta desperata och ensamma mammor men det förekommerm även fruar som bedrar sina män eller vill endast ha lite kul utanför sitt nuvarande äktenskap. De kan vara dina grannar eller någon du känner. Håller du med att hålla kvinnornas identitet hemlig?",
    txt6: "Dessa kvinnor har bett oss att inte bli kopplade ihop med män som söker en seriös relation . De önskar endast komma i kontakt med män som vill ha snabb sex. Inga dejter. Håller du med den här begäran?",
    txt8: "Är du minst 25 år gammal? Kvinnorna har begärt att vi inte låter de yngre än 25 åt kontakta dessa på grund av tidigare obefogade beteenden från yngre män.",
    txt10:
      "Eftersom du kommer att se explicita bilder måste vi veta att du är över 25.",
    txt12: "Vänligen ange ditt användarnamn",
    txt14: "Vänligen ange din e-postadress",
    txt16: "Vänligen ange ditt lösenord",
    txt18:
      'Du kan nu beakta vår lista och foton på kvinnor inom ditt närområde. Återigen, säkerställ att du respekterar deras integritet och håller deras identitet hemligt. Klicka på "Fortsätt" och sök på grundval.',
    btnContinue: "Fortsätta",
    btnYes: "JA",
    btnNo: "NEJ",
    btnNext: "nästa",
    btnBack: "Tillbaka",
    adult: "endast vuxen",
    follow: "Prenumerera",
  },
  ja: {
    txt1: "警告！",
    txt3: "質問 1",
    txt5: "質問 2",
    txt7: "質問 3",
    txt9: "年齢",
    txt11: "ユーザー名",
    txt13: "Eメール",
    txt15: "パスワード",
    txt17: "ありがとうございます！",
    txt2: "ヌード写真が含まれます。ご注意ください。",
    txt4: "これらの女性の多くは、刺激を求めているシングルマザーや人妻です。これらの女性は、あなたの近所の住人または知人かもしれません。これらの女性の身元情報を秘密にすることに同意しますか？",
    txt6: "これらの女性は、「交際関係」を求めている男性を求めていません。これらの女性は、セックスだけの関係を求めています。デート相手を探しているわけではありません。あなたはこのリクエストに同意できますか？",
    txt8: "あなたは少なくとも25歳ですか？これらの女性は、過去に若い男性から失礼な態度を取られたため、25歳未満の男性とのコンタクトを求めていません。",
    txt10:
      "過激な画像が含まれるため、あなたの年齢が25歳以上であることを確認しなければなりません。",
    txt12: "あなたのユーザー名を入力してください。",
    txt14: "あなたのEメールを入力してください。",
    txt16: "あなたのパスワードを入力してください。",
    txt18:
      "あなたの地域にいる女性のリストと写真を見ることができます。女性の身元情報に関しては、秘密にしてください。「続行」ボタンをクリックして、あなたの回答に基づいて検索します。",
    btnContinue: "続行",
    btnYes: "はい",
    btnNo: "いいえ",
    btnNext: "次へ",
    btnBack: "戻る",
    adult: "成人のみ",
    follow: "購読する",
  },
  fa: {
    txt1: "هشدار!",
    txt3: "1 سوال",
    txt5: "2 سوال",
    txt7: "3 سوال",
    txt9: "سن",
    txt11: "نام کاربری",
    txt13: "پست الکترونیک",
    txt15: "کلمه عبور",
    txt17: "متشکرم!",
    txt2: "عکس های برهنه را مشاهده خواهید کرد. لطفا باهوش باشید.",
    txt4: "بسیاری از این زنان مادران مجرد هستند و همسران تقلب به دنبال سرگرمی هستند. آنها می توانند همسایگان شما یا شخصی باشند که می شناسید. آیا قبول دارید که هویت این زنان راز مخفی نگه دارید؟",
    txt6: 'این زنان از ما خواسته اند كه اجازه ندهیم مردانی كه به دنبال "رابطه" هستند. آنها فقط خواهان رابطه جنسی سریع هستند. قرار ملاقات نیست آیا با این درخواست موافق هستید؟',
    txt8: "ایا شما حداقل 25 سال دارید؟ زنان درخواست کرده اند که ما به دلیل رفتار ناشایست گذشته مردان جوان ، اجازه ندهیم افراد جوانتر از 25 سال با آنها ارتباط برقرار کنند.",
    txt10:
      "از آنجا که تصاویر صریح را خواهید دید ، باید بدانیم که شما بالای 25 سال دارید.",
    txt12: "لطفاً نام کاربری خود را وارد کنید",
    txt14: "لطفا ایمیل خود را وارد کن",
    txt16: "لطفا رمز عبور خود را وارد کنید",
    txt18:
      'اکنون می توانید لیست و عکسهای ما از زنانی که در منطقه شما هستند را ببینید. باز هم ، لطفا هویت آنها را مخفی نگه دارید. بر روی دکمه "ادامه" کلیک کرده و بر اساس پاسخ های خود جستجو کنید.',
    btnContinue: "ادامه هید",
    btnYes: "بله",
    btnNo: "خیر",
    btnNext: "بازگشت",
    btnBack: "بعدی",
    adult: "فقط بزرگسالان",
    follow: "اشتراک در",
  },
  id: {
    txt1: "PERINGATAN!",
    txt3: "pertanyaan 1",
    txt5: "pertanyaan 2",
    txt7: "pertanyaan 3",
    txt9: "USIA",
    txt11: "Nama pengguna",
    txt13: "Surel",
    txt15: "Kata sandi",
    txt17: "Terima kasih!",
    txt2: "Anda akan melihat foto-foto telanjang. Harap berhati-hati.",
    txt4: "Banyak dari wanita ini adalah ibu tunggal yang putus asa dan istri selingkuh yang mencari kesenangan. Mereka bisa jadi tetangga Anda atau seseorang yang Anda kenal. Apakah Anda setuju untuk merahasiakan identitas wanita-wanita ini?",
    txt6: 'Para wanita ini meminta kami untuk tidak mengizinkan pria yang mencari "hubungan". Mereka hanya menginginkan seks cepat. Tidak berkencan. Apakah Anda menyetujui permintaan ini?',
    txt8: "Apakah Anda setidaknya berumur 25 tahun? Para wanita telah meminta agar kami tidak membiarkan mereka yang berusia di bawah 25 tahun menghubungi mereka karena perilaku kasar masa lalu oleh pria yang lebih muda.",
    txt10:
      "Karena Anda akan melihat gambar eksplisit, kami perlu tahu bahwa Anda berusia di atas 25 tahun.",
    txt12: "Silakan masukkan nama pengguna Anda",
    txt14: "Masukkan email Anda",
    txt16: "Silakan masukkan kata sandi Anda",
    txt18:
      'Anda sekarang dapat melihat daftar dan foto-foto wanita yang ada di daerah Anda. Sekali lagi, tolong jaga kerahasiaan identitas mereka. Klik tombol "Lanjutkan" dan cari berdasarkan jawaban Anda.',
    btnContinue: "Terus",
    btnYes: "IYA",
    btnNo: "TIDAK",
    btnNext: "Berikutnya",
    btnBack: "Kembali",
    adult: "dewasa saja",
    follow: "Langganan",
  },
};
$(document).ready(function () {
  var langBrowser =
    navigator.language || (navigator.languages && navigator.languages[0]),
    param = langs[langBrowser];
  if (param == undefined && langBrowser && langBrowser.length > 0) {
    var parsedLang = langBrowser.slice(0, 2);
    if (langs[parsedLang]) {
      param = langs[parsedLang];
    }
  }
  if (param == undefined) {
    param = langs["en"];
    // 'en' - default language, if you want change language, please select in object abbreviation. Example: 'fr', 'ru' etc.
    $(".txt1").text(param.txt1);
    $(".txt2").text(param.txt2);
    $(".txt3").text(param.txt3);
    $(".txt4").text(param.txt4);
    $(".txt5").text(param.txt5);
    $(".txt6").text(param.txt6);
    $(".txt7").text(param.txt7);
    $(".txt8").text(param.txt8);
    $(".txt9").text(param.txt9);
    $(".txt10").text(param.txt10);
    $(".txt11").text(param.txt11);
    $(".txt12").text(param.txt12);
    $(".txt13").text(param.txt13);
    $(".txt14").text(param.txt14);
    $(".txt15").text(param.txt15);
    $(".txt16").text(param.txt16);
    $(".txt17").text(param.txt17);
    $(".txt18").text(param.txt18);
    $(".btnContinue").text(param.btnContinue);
    $(".btnBack").text(param.btnBack);
    $(".btnNext").text(param.btnNext);
    $(".btnYes").text(param.btnYes);
    $(".btnNo").text(param.btnNo);
    $(".follow").text(param.follow);
  } else {
    $(".txt1").text(param.txt1);
    $(".txt2").text(param.txt2);
    $(".txt3").text(param.txt3);
    $(".txt4").text(param.txt4);
    $(".txt5").text(param.txt5);
    $(".txt6").text(param.txt6);
    $(".txt7").text(param.txt7);
    $(".txt8").text(param.txt8);
    $(".txt9").text(param.txt9);
    $(".txt10").text(param.txt10);
    $(".txt11").text(param.txt11);
    $(".txt12").text(param.txt12);
    $(".txt13").text(param.txt13);
    $(".txt14").text(param.txt14);
    $(".txt15").text(param.txt15);
    $(".txt16").text(param.txt16);
    $(".txt17").text(param.txt17);
    $(".txt18").text(param.txt18);
    $(".btnContinue").text(param.btnContinue);
    $(".btnBack").text(param.btnBack);
    $(".btnNext").text(param.btnNext);
    $(".btnYes").text(param.btnYes);
    $(".btnNo").text(param.btnNo);
    $(".follow").text(param.follow);
  }
  (function initStepbox() {
    var $stepBox = $(".stepbox"),
      $stepBoxStep = $stepBox.children(".step");
    $stepBoxStep.find(".next").click(function (e) {
      e.preventDefault();
      changeStep();
    });

    function changeStep() {
      var $currentStep = $stepBoxStep.filter(".current");
      $currentStep.removeClass("current");
      $currentStep.next().addClass("current");
      $(".progress .bar").animate({
        width: "+=20%",
      });
    }
    function prevStep() {
      var $currentStep = $stepBoxStep.filter(".current");
      $currentStep.removeClass("current");
      $currentStep.prev().addClass("current");
      $(".progress .bar").animate({
        width: "-=20%",
      });
    }
    $(".btn-back").on("click", function () {
      prevStep();
    });
  })();
});
